name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"

          if [ -z "$latest_tag" ]; then
            echo "tag=v1.0.0" >> $GITHUB_OUTPUT
          else
            version=$(echo "$latest_tag" | sed 's/v//')
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
            echo "tag=$new_tag" >> $GITHUB_OUTPUT
          fi
      
      -name: Set up Python
       uses: actions/setup-python@v4
       with:
        python-version: '3.11'
      
      -name: Run test.py
       run: python test.py
       
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
